language: scala
scala:
- 2.12.4
jdk:
- oraclejdk8
- oraclejdk9
script:
- "sbt compile"
cache:
  directories:
  - "$HOME/.ivy2/cache"
before_cache:
- rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm

# See https://blog.travis-ci.com/2014-03-13-slack-notifications/
# notifications:
#   slack:
#     secure: TODO